import { HistoricalPeriod } from "../historical_period/historical-period.models";
import { ApiDino } from "./api/api-dino.models";
import { Dino } from "./dino.models";


export function transformDino(dinoEl: ApiDino, selectedHistoricalPeriod?: HistoricalPeriod): Dino {
    //In this function:
     //I am deleting the createdAt and updatedAt properties which are the ones I have decided not to use in my dino.models.ts (it is info generated by Mongo)
    delete dinoEl.createdAt && dinoEl.updatedAt;
    //return the dinoEl without the createdAt field and updatedAt
    return {
        ...dinoEl,//get the info from ApiDino and make a copy of it
        historicalPeriod: selectedHistoricalPeriod ? selectedHistoricalPeriod : {period: dinoEl.historicalPeriod}
};
}